sudo: required

services:
  - docker
  
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

language: node_js

node_js:
 - "6"

after_success:
 - sh .travis/dockerizer.sh
 - sh .travis/trigger_new_deployment.sh
